### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by istrait** [PiPass/blockpage#47]
Getting an error when I use the install to put pipass on my raspberry pi..

Here is the console output...
PiPass installer

First run of installer...
PiPass installer
```
Root user check...
Root user check complete
rm: cannot remove 'setup.php.*': No such file or directory
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html
Confirmation: Is this the correct document root? (/var/www/html) [y/n]
y
DR check succeeded, now installing PiPass...
Current php user is pi.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
Adding line to /etc/sudoers...
Permissions have been set up successfully!
Setting up Git repository and collecting PiPass files.
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 2350 (delta 4), reused 13 (delta 1), pack-reused 2330
Receiving objects: 100% (2350/2350), 4.53 MiB | 171.00 KiB/s, done.
Resolving deltas: 100% (639/639), done.
From https://github.com/roenw/pipass
 * [new branch]      admin        -> origin/admin
 * [new branch]      locales-beta -> origin/locales-beta
 * [new branch]      master       -> origin/master
 * [new tag]         v1.3.5       -> v1.3.5
 * [new tag]         v1.3         -> v1.3
fatal: not a git repository (or any of the parent directories): .git
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/setup.php:87
Stack trace:
#0 /home/pi/setup.php(97): get_data('https://apps.ro...')
#1 /home/pi/setup.php(50): install()
#2 /home/pi/setup.php(24): preInstall()
#3 {main}
  thrown in /home/pi/setup.php on line 87
```

Second Run...
```
Root user check...
Root user check complete
rm: cannot remove 'setup.php.*': No such file or directory
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html
Confirmation: Is this the correct document root? (/var/www/html) [y/n]
y
DR check succeeded, now installing PiPass...
Current php user is pi.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
Adding line to /etc/sudoers...
Permissions have been set up successfully!
Setting up Git repository and collecting PiPass files.
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 2350 (delta 4), reused 13 (delta 1), pack-reused 2330
Receiving objects: 100% (2350/2350), 4.53 MiB | 171.00 KiB/s, done.
Resolving deltas: 100% (639/639), done.
From https://github.com/roenw/pipass
 * [new branch]      admin        -> origin/admin
 * [new branch]      locales-beta -> origin/locales-beta
 * [new branch]      master       -> origin/master
 * [new tag]         v1.3.5       -> v1.3.5
 * [new tag]         v1.3         -> v1.3
fatal: not a git repository (or any of the parent directories): .git
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/setup.php:87
Stack trace:
#0 /home/pi/setup.php(97): get_data('https://apps.ro...')
#1 /home/pi/setup.php(50): install()
#2 /home/pi/setup.php(24): preInstall()
#3 {main}
  thrown in /home/pi/setup.php on line 87
```

Looks like it does not like curl for some reason... 

Here is the curl version information from the command line.

```
pi@raspberrypi:/var/www/html $ curl -V
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

Edited by roenw for formatting fixes.

**Comment by istrait** [comment]
Here is my curl version information

pi@raspberrypi:/var/www/html $ curl -V
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by roenw** [comment]
Hello Ian. There is no error. Those commands are there to remove old, possibly stale versions of setup.php (as wget will save extra copies as setup.php.x, e.g. setup.php.1) and there is no cause for concern. 

Thank you for bringing this to my attention, we will make sure to redirect those commands’ output to /dev/null in the future. 

Enviado desde mi iPhone

**Comment by istrait** [comment]
The install process stops at that error and pipass does not seem to get installed.
I get a 400 bad request when I hit the blockpage.

Setup process does not go beyond line 96.

**Comment by roenw** [comment]
Sorry, I didn't see the error at the end. 
Can you try to create a php file on your system with the following content.

```
<?php
function get_data($url) {
    $ch = curl_init();
    $timeout = 5;
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
    $data = curl_exec($ch);
    curl_close($ch);
    return $data;
}
$latestVersion = get_data("https://apps.roen.us/pipass/currentversion/");
echo "You have php7.0-curl or php-curl installed. Data: latest version v$latestVersion\n";
?>
```

And tell me the output?

**Comment by istrait** [comment]
php test.php
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/test.php:3
Stack trace:
#0 /var/www/html/test.php(12): get_data('https://apps.ro...')
#1 {main}
  thrown in /var/www/html/test.php on line 3

**Comment by roenw** [comment]
Are you sure you have php-curl or php7.0-curl installed?

**Comment by istrait** [comment]
I just ran sudo apt-get install php-curl and now it gets to the end of the install...

**Comment by roenw** [comment]
End of the PiPass install or php-curl install?
