### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() during install

### ISSUE THREAD

**Issue by nbgibson** [PiPass/blockpage#50]
**Describe the bug**
Exited out of the initial install process, retrying the install throws errors due to remnants left from first attempt. See output below.

**To Reproduce**
1. Run (the modern) install script.
2. Ctrl + C out when asked to confirm webroot location
3. Re run install command

**Expected behavior**
Normal installation procedures

**Output**
```
PiPass installer

Root user check...
Root user check complete
rm: cannot remove 'setup.php.*': No such file or directory
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)

Confirmation: Is this the correct document root? () [y/n]
n

 **WARN: User aborted. Exiting...**
```
```
pi@pihole:~ $ bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)
--2019-08-12 13:28:01--  https://raw.githubusercontent.com/roenw/PiPass/master/setup/setup.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5080 (5.0K) [text/plain]
Saving to: ‘setup.php.1’

setup.php.1                100%[======================================>]   4.96K  --.-KB/s    in 0.004s   

2019-08-12 13:28:02 (1.26 MB/s) - ‘setup.php.1’ saved [5080/5080]












######    ######
#     # # #     #   ##    ####   ####
#     # # #     #  #  #  #      #
######  # ######  #    #  ####   ####
#       # #       ######      #      #
#       # #       #    # #    # #    #
#       # #       #    #  ####   ####
PiPass installer

Root user check...
Root user check complete
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html
Confirmation: Is this the correct document root? (/var/www/html) [y/n]
y
DR check succeeded, now installing PiPass...
Current php user is pi.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
Adding line to /etc/sudoers...
Permissions have been set up successfully!
Setting up Git repository and collecting PiPass files.
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 2350 (delta 4), reused 13 (delta 1), pack-reused 2330
Receiving objects: 100% (2350/2350), 4.53 MiB | 940.00 KiB/s, done.
Resolving deltas: 100% (639/639), done.
From https://github.com/roenw/pipass
 * [new branch]      admin        -> origin/admin
 * [new branch]      locales-beta -> origin/locales-beta
 * [new branch]      master       -> origin/master
 * [new tag]         v1.3.5       -> v1.3.5
 * [new tag]         v1.3         -> v1.3
fatal: not a git repository (or any of the parent directories): .git
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/setup.php:87
Stack trace:
#0 /home/pi/setup.php(97): get_data('https://apps.ro...')
#1 /home/pi/setup.php(50): install()
#2 /home/pi/setup.php(24): preInstall()
#3 {main}
  thrown in /home/pi/setup.php on line 87
```
```
pi@pihole:~ $ bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)
--2019-08-12 13:32:15--  https://raw.githubusercontent.com/roenw/PiPass/master/setup/setup.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5080 (5.0K) [text/plain]
Saving to: ‘setup.php.1’

setup.php.1                          100%[=====================================================================>]   4.96K  --.-KB/s    in 0.004s  

2019-08-12 13:32:15 (1.28 MB/s) - ‘setup.php.1’ saved [5080/5080]












######    ######
#     # # #     #   ##    ####   ####
#     # # #     #  #  #  #      #
######  # ######  #    #  ####   ####
#       # #       ######      #      #
#       # #       #    # #    # #    #
#       # #       #    #  ####   ####


PiPass installer

Root user check...
Root user check complete
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html
Confirmation: Is this the correct document root? (/var/www/html) [y/n]
y
DR check succeeded, now installing PiPass...
Current php user is pi.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
/etc/sudoers is already set up. No need to add another line.
Setting up Git repository and collecting PiPass files.
fatal: remote origin already exists.
fatal: not a git repository (or any of the parent directories): .git
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/setup.php:87
Stack trace:
#0 /home/pi/setup.php(97): get_data('https://apps.ro...')
#1 /home/pi/setup.php(50): install()
#2 /home/pi/setup.php(24): preInstall()
#3 {main}
  thrown in /home/pi/setup.php on line 87
```

**Desktop (please complete the following information):**
 - OS: Rasbian Buster
 - Browser: N/A
 - Version: Current

**Additional context**
This one is on me; please advise what/where I need to purge to get everything back to zero.

**Comment by roenw** [comment]
@nbgibson It looks like you don't have ``php7.0-curl`` installed.
Run ``sudo apt install php7.0-curl``.

**Comment by nbgibson** [comment]
It seems that php7.0-curl doesn't have a release candidate for Rasbian Buster. Can you advise?

**Comment by roenw** [comment]
I don't want to sound condescending, but did you try ``sudo apt update`` yet? Always helps :)

**Comment by scorpionson** [comment]
@nbgibson I was able to solve in Buster by installing php7.3
php7.0 is not available for Buster and 7.3 is not installed by default.
`sudo apt-get install php7.3-fpm`
Then run install again.

**Comment by roenw** [comment]
@scorpionson Wow, I’m stupid lol

**Comment by nbgibson** [comment]
Ok I've gotten a successful install now; you were both on the right track. ```sudo apt-get install php7.3-fpm``` still threw the same error during install, but ```sudo apt install php7.3-curl``` did the trick. Knowing my luck I have it pointed at the wrong webroot, but that's very much my problem to solve. Cheers!

**Comment by nbgibson** [comment]
Tweaked the issue title for discoverability should some other folks run into the same issue down the line.
