### ISSUE TITLE
PiPass install fails with 'remote origin already exists'

### ISSUE THREAD

**Issue by serendrewpity** [PiPass/blockpage#51]
Install attempted with command 'bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)' and entered /var/www/html for doc root of Lighttpd but the output below was generated which displays a fatal error...

```
######    ######                       
#     # # #     #   ##    ####   ####  
#     # # #     #  #  #  #      #      
######  # ######  #    #  ####   ####  
#       # #       ######      #      # 
#       # #       #    # #    # #    # 
#       # #       #    #  ####   ####  


PiPass installer

Root user check...
Root user check complete
rm: cannot remove 'setup.php.*': No such file or directory
mv: '/root/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html
Confirmation: Is this the correct document root? (/var/www/html) [y/n]
y
DR check succeeded, now installing PiPass... 
Current php user is root.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
/etc/sudoers is already set up. No need to add another line.
Setting up Git repository and collecting PiPass files.
fatal: remote origin already exists.
fatal: not a git repository (or any of the parent directories): .git
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/setup.php:78
Stack trace:
#0 /root/setup.php(87): get_data('https://apps.ro...')
#1 /root/setup.php(44): install()
#2 /root/setup.php(20): preInstall()
#3 {main}
  thrown in /root/setup.php on line 78
```

Noticed some differences between the two files below but they both generated the same error...
https://raw.githubusercontent.com/roenw/PiPass/master/setup/setup.php
https://github.com/roenw/PiPass/tree/master/setup/setup.php

Please investigate...

**Comment by roenw** [comment]
Sorry, this issue must’ve slipped through my inbox. The problem is that you’re missing php-curl. If you are running a Debian-based system which it appears you are, run ``sudo apt update && sudo apt install php-curl`` and the installer should succeed. 

Curl is used to check for PiPass updates.
