### ISSUE TITLE
install.sh

### ISSUE THREAD

**Issue by Brickme** [PiPass/blockpage#55]
```
pi@raspberrypi:~ $ su
Password:
root@raspberrypi:/home/pi# bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)
--2019-09-18 14:08:27--  https://raw.githubusercontent.com/roenw/PiPass/master/setup/setup.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.192.133, 151.101.0.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5080 (5.0K) [text/plain]
Saving to: ‘setup.php.1’

setup.php.1         100%[===================>]   4.96K  --.-KB/s    in 0.001s

2019-09-18 14:08:27 (4.54 MB/s) - ‘setup.php.1’ saved [5080/5080]












######    ######
#     # # #     #   ##    ####   ####
#     # # #     #  #  #  #      #
######  # ######  #    #  ####   ####
#       # #       ######      #      #
#       # #       #    # #    # #    #
#       # #       #    #  ####   ####


PiPass installer

Root user check...
Root user check complete
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html/pihole
Confirmation: Is this the correct document root? (/var/www/html/pihole) [y/n]
y
DR check succeeded, now installing PiPass...
Current php user is pi.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
/etc/sudoers is already set up. No need to add another line.
Setting up Git repository and collecting PiPass files.
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 2382 (delta 20), reused 15 (delta 1), pack-reused 2330
Receiving objects: 100% (2382/2382), 4.54 MiB | 5.88 MiB/s, done.
Resolving deltas: 100% (655/655), done.
From https://github.com/roenw/pipass
 * [new branch]      admin        -> origin/admin
 * [new branch]      locales-beta -> origin/locales-beta
 * [new branch]      master       -> origin/master
 * [new tag]         v1.3         -> v1.3
fatal: not a git repository (or any of the parent directories): .git
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/setup.php:87
Stack trace:
#0 /home/pi/setup.php(97): get_data('https://apps.ro...')
#1 /home/pi/setup.php(50): install()
#2 /home/pi/setup.php(24): preInstall()
#3 {main}
  thrown in /home/pi/setup.php on line 87
root@raspberrypi:/home/pi#

```
Any advice? I am not 100% sure whats going on with install.sh

**Comment by roenw** [comment]
Nothing is going wrong, you’re just missing a prerequisite software. See #50

We will make the installation of this software automatic soon.

**Comment by Brickme** [comment]
`sudo apt-get install php-curl`
This was my issue.

```
`root@raspberrypi:/home/pi# bash <(wget -qO- https://kubrick.roen.us/pipass/scrip                                                                                                                                                             ts/install.sh)
--2019-09-18 14:20:14--  https://raw.githubusercontent.com/roenw/PiPass/master/s                                                                                                                                                             etup/setup.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.4.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.4.13                                                                                                                                                             3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5080 (5.0K) [text/plain]
Saving to: ‘setup.php.1’

setup.php.1         100%[===================>]   4.96K  --.-KB/s    in 0.001s

2019-09-18 14:20:14 (4.40 MB/s) - ‘setup.php.1’ saved [5080/5080]












######    ######
#     # # #     #   ##    ####   ####
#     # # #     #  #  #  #      #
######  # ######  #    #  ####   ####
#       # #       ######      #      #
#       # #       #    # #    # #    #
#       # #       #    #  ####   ####


PiPass installer

Root user check...
Root user check complete
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html/pihole
Confirmation: Is this the correct document root? (/var/www/html/pihole) [y/n]
y
DR check succeeded, now installing PiPass...
Current php user is pi.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
/etc/sudoers is already set up. No need to add another line.
Setting up Git repository and collecting PiPass files.
fatal: remote origin already exists.
fatal: not a git repository (or any of the parent directories): .git
Files downloaded. Moving to latest stable release v1.3
Note: checking out 'tags/v1.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a34f247 beta --> master - Update functionality (#2)
Lighttpd web server detected. Modifying 404 redirects.
No lighttpd.conf backup found for PiPass. Backing up before modifying.
Modifying PiHole FTL to BLOCKINGMODE=IP
No pihole-FTL.conf backup found for PiPass. Backing up before modifying.
Selected version v1.3
rm: cannot remove '.github': No such file or directory
rm: cannot remove 'docs': No such file or directory
rm: cannot remove 'mkdocs.yml': No such file or directory
Removed redundant files.
 Installation complete.
root@raspberrypi:/home/pi#
`
```
*Solved*
